# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'MTIG JS'
tagline:          'MTIG 17'
description:      'Programación con JavaScript'
url:              http://xguaita.github.io/mtig-js
baseurl:          /mtig-js

author:
  name:           'Xisco Guaita'
  url:            https://twitter.com/xguaita

paginate:         5

# Custom vars

github:
  repo:           https://github.com/xguaita/mtig-js
